header.go

Changed validation to lowercase the token type and algorithm before performing validity checks.

Changed the algorithm to be ed25519 rather than introduce a new type.

---

account_claims_test.go
activation_claims_test.go
exports.go
exports_test.go
imports.go
imports_test.go
types.go

Converted ExportType to enum

---

account_claims_test.go
activation_claims_test.go
exports.go
exports_test.go
imports.go
imports_test.go

NamedSubject moved, TokenReq added to Export

---

imports.go
imports_test.go

Removed TokenURL and just use Token, added timeout to http.Get()

Token updates.

---

claims.go
decoder_test.go
header.go

Change to base64.RawURLEncoding

---

claims.go
decoder_test.go
header.go

Alberto's code to isolated the base 64 stuff + a test.

Isolate base64 codec

---

imports.go

This is a document only change.

FIX #28 - Added documentation explaining Subject/To fields in an import.

---

account_claims.go
account_claims_test.go
activation_claims_test.go
operator_claims.go
operator_claims_test.go
user_claims_test.go

Refactored signing keys to use StringList and simplify tooling downstream

---

types.go
user_claims.go
user_claims_test.go

Added in ResponsePermissions

---

account_claims.go
account_claims_test.go
exports.go
exports_test.go
revocation_list.go

Revocation logic is in a new RevocaionList type

Added revocation maps in account and exports

---

creds_utils.go
exports.go
exports_test.go

Added tests for response types
Fixed a few doc comments while i was in here

Added response types to exports

---

go.mod
go.sum

Bump version, update dependencies

---

header.go
imports.go
imports_test.go

Detect duplicate service to subjects on imports

---

go.mod
go.sum

Update go.mod to latest NKeys release

---

operator_claims.go
operator_claims_test.go

Adding system_account identity to operator`

---

.travis.yml

Release v1.0.0

---

.travis.yml

rolled back to skip_cleanup on travis deploy, as cleanup doesn't do what it says

---

account_claims.go
account_claims_test.go
v2/account_claims.go
v2/account_claims_test.go

Moving default permissions to v2

---

v2/account_claims.go
v2/account_claims_test.go
v2/activation_claims.go
v2/activation_claims_test.go
v2/decoder_account.go
v2/decoder_activation.go
v2/decoder_migration_test.go
v2/decoder_user.go
v2/exports.go
v2/exports_test.go
v2/go.mod
v2/go.sum
v2/imports_test.go
v2/types.go
v2/user_claims.go
v2/user_claims_test.go

this is part of the resolution for #1552 in nats-server https://github.com/nats-io/nats-server/issues/1552

Add export threshold, user limits, deprecate Max and activation limits

---

v2/decoder_migration_test.go
v2/go.mod
v2/go.sum

Remove dependency dragged in by code completion

---

v2/account_claims.go
v2/user_claims.go

And thus remove them from the user jwt

Move connection limits into account limits section

---

v2/decoder_migration_test.go
v2/types.go
v2/user_claims.go
v2/user_claims_test.go

Turn scr into list and add locale for time ranges

---

go.mod
go.sum
v2/account_claims.go
v2/account_claims_test.go
v2/decoder_account.go
v2/decoder_migration_test.go
v2/decoder_operator.go
v2/go.sum
v2/operator_claims.go
v2/types.go

Removing Identity from jwt

---

v2/genericclaims_test.go
v2/genericlaims.go

Fix genericClaim ClaimType

---

go.mod
v2/decoder_account.go
v2/decoder_activation.go
v2/decoder_migration_test.go
v2/decoder_operator.go
v2/decoder_user.go
v2/go.sum

Set Version after parsing V1

---

v2/user_claims.go

Add MQTT connection type constant

---

v2/exports.go
v2/imports.go

Add validation error for nil import/export

---

v2/validation.go
validation.go

Return non blocking validation results as slice of strings

---

exports.go
v2/exports.go
v2/exports_test.go

Fixes #104
Same as for other revocations

Fixed documentation issue for jwt activation revocation

---

revocation_list.go

[FIXED] Make IsRevoked check inclusive

---

exports.go

[FIXED] Documentation issue for jwt activation revocation

---

header.go

Release v1.1.0

---

README.md
header.go
types_test.go
v2/header.go
v2/types_test.go

Release v1.2.0

---

header.go

Release v1.2.2

---

v2/imports.go
v2/imports_test.go

[Fixed] import token validation:  validate activation/allow signing keys

---

v2/activation_claims.go
v2/imports.go
v2/imports_test.go

On import validation avoid time check on activation token

---

v2/activation_claims.go
v2/activation_claims_test.go
v2/imports.go
v2/imports_test.go

[Added] the ability to have wild card exports/imports

---

v2/imports.go

added accessor to read To without deprecation warning

---

v2/types.go
v2/types_test.go

This change also allows restrictions on queues

[fixed] missing validation for permissions

---

v2/account_claims.go
v2/account_claims_test.go

Fixed default value for js limits to be 0 (disabled)

---

v2/operator_claims.go

[added] flag enforcing subordinate objects be signed with signing keys

---

v2/exports.go
v2/types.go
v2/types_test.go

[added] advertise flag to exports and extending max description length

---

v2/imports.go
v2/imports_test.go

[removed] jwt activation token as url and corresponding download

---

v2/account_claims.go
v2/account_claims_test.go

renamed OptCluster to Cluster

---

v2/header.go

Release v2.0.1

---

creds_utils.go
v2/creds_utils.go
v2/creds_utils_test.go

adding synadia operator unit test

---

README.md
v2/header.go

Release v2.0.2

---

v2/imports_test.go
v2/types.go

[fixed] wildcard counting issue on import validation

---

v2/header.go

Release v2.0.3

---

.travis.yml

fix: change travis job to use test go.mod file

fix: change travis job to use test go.mod file

---

.travis.yml
v2/header.go

Release v2.1.0

---

v2/header.go

Release v2.2.0

---

v2/account_claims.go
v2/account_claims_test.go
v2/decoder_account.go

[FEATURE] Adding support for js max bytes required

---

v2/account_claims.go
v2/account_claims_test.go
v2/decoder_account.go

rename struct member HaResources to HAResources

---

.travis.yml
v2/test/decoder_migration_test.go
v2/test/genericclaims_test.go

Update travis to Go 1.17

---

v2/account_claims.go
v2/account_claims_test.go

Adding max_max_bytes to limit the maximum value for max bytes

---

v2/account_claims.go
v2/account_claims_test.go

And removing dependency on MaxBytesRequired

Switching MaxStreamBytes to Disk/Memory

---

.travis.yml
account_claims_test.go
activation_claims_test.go
cluster_claims_test.go
operator_claims_test.go
server_claims_test.go
user_claims_test.go
v2/account_claims.go
v2/account_claims_test.go
v2/activation_claims_test.go
v2/operator_claims_test.go
v2/user_claims_test.go

Adding max_ack_pending stream limit

---

v2/activation_claims.go

fix validation text

---

.travis.yml
v2/header.go

Release v2.3.0

---

v2/account_claims.go
v2/account_claims_test.go

Add in support for external authorization for accounts.

---

v2/authorization_claims.go
v2/authorization_claims_test.go
v2/claims.go
v2/decoder.go
v2/decoder_authorization.go

These are for external authentication request from a NATS server.

Added in an authorization request claims.

---

.travis.yml
creds_utils.go
exports.go
go.mod
imports.go
v2/creds_utils.go
v2/exports.go
v2/go.mod
v2/go_test.mod
v2/validation.go
validation.go

Made some updates to the lib.
Updated go vet and go fmt changes.
Remove ioutil usage.
Updated travis to go 1.19 and 1.18 versions for tests.
Updated go modules version to 1.18.

Some Updates

---

v2/authorization_claims.go
v2/authorization_claims_test.go
v2/claims.go
v2/decoder_authorization.go

[CHANGE] remove AuthorizationResponse/Claims - and instead rely on headers and a simple User jwt response

simplify AuthorizationResponse

---

v2/account_claims.go
v2/account_claims_test.go

Resolves https://github.com/nats-io/jwt/issues/201

remove wildcard validation from mappings

---

README.md
v2/example_test.go

[DOC] changed the main example to show a basic operator->account->user setup that actually runs on a server

better initial example

---

v2/account_claims.go
v2/account_claims_test.go

Fixes https://github.com/nats-io/nsc/issues/657

[FIX] accounting for mapping weights in cluster should be handled separate
